In [1]:
import torch
from torch import nn


In [8]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(2,2)
        self.activation1 = nn.Tanh()
        self.layer2 = nn.Linear(2,1)
        self.activation2 = nn.Tanh()
    
    def forward(self, x):
        x = self.layer1(x)
        x = self.activation1(x)
        x = self.layer2(x)
        x = self.activation2(x)
        return x


In [13]:
model = MyModel()
lossfn = nn.MSELoss()

In [12]:
model(torch.tensor([[1,1]], dtype=torch.float32))

tensor([[0.4521]], grad_fn=<TanhBackward0>)

In [25]:
torch.tensor([0]).logical_xor(torch.tensor([1]))

tensor([True])

In [22]:
xor = lambda x1, x2 : x1 != x2
def generate_batch(batchsize):
    return torch.randint(2, (batchsize, 2,))
    for i in range(batchsize):
        x1 = torch.randint(2, (1,))
        x2 = torch.randint(2, (1,))
        y = xor(x1, x2)
        y = torch.tensor(y, dtype=torch.float32)
        print(x1,x2, y)
def calculate_output():
    torch.logical_xor

generate_batch(10)




tensor([[0, 0],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 0],
        [1, 1],
        [0, 1],
        [1, 1],
        [0, 0],
        [1, 1]])