In [1]:
import torch
import numpy as np

In [8]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [12]:
np_array = np.array(x_data)
x_from_np = torch.from_numpy(np_array)
x_from_np

array([[1, 2],
       [3, 4]])

In [14]:
x_like_ones = torch.ones_like(x_data)
x_like_ones

tensor([[1, 1],
        [1, 1]])

In [16]:
x_like_zeros = torch.zeros_like(x_data)
x_like_zeros

tensor([[0, 0],
        [0, 0]])

In [19]:
x_like_random_tensor = torch.rand_like(x_data, dtype=torch.float)
x_like_random_tensor.dtype

torch.float32

In [20]:
# giving the shape parameters
shape = (2,3,)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor = torch.rand(shape)

print(f"ones = {ones_tensor}")
print(f"zeros = {zeros_tensor}")
print(f"random = {rand_tensor}")

ones = tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros = tensor([[0., 0., 0.],
        [0., 0., 0.]])
random = tensor([[0.8263, 0.1384, 0.2362],
        [0.4757, 0.2387, 0.1911]])


In [21]:
# properties of the tensor
tensor = torch.rand(4,2)

print(f"Shape of tensor = {tensor.shape}")
print(f"Datatype of tensor = {tensor.dtype}")
print(f"Device of tensor = {tensor.device}")

Shape of tensor = torch.Size([4, 2])
Datatype of tensor = torch.float32
Device of tensor = cpu


In [26]:
# if torch.device('mps').is_available():
    # print("It is available")
print(dir(torch.device('mps')))


['__class__', '__delattr__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'index', 'type']
